const TOPICS = {
  inflation:{icon:'inflation', title:'L’inflation', short:'Pourquoi tout coûte plus cher', minutes:4,
    one:'L’inflation, c’est la hausse générale et durable des prix. Avec le même billet de 20 €, on achète un peu moins qu’avant.',
    analogy:'Imagine une fête où tout le monde reçoit plus de bonbons, mais où le gâteau reste de la même taille. Chacun veut sa part, alors le « prix » d’une part grimpe. Quand il y a plus d’argent en circulation que de choses à acheter, les prix montent.',
    how:['Les prix montent quand la demande dépasse ce que les entreprises peuvent produire (après le Covid, par exemple).','Ils montent aussi quand produire coûte plus cher : énergie, matières premières, salaires.','Une petite inflation (autour de 2 % par an) est jugée saine : elle encourage à consommer et à investir sans affoler personne.','Trop d’inflation ronge l’épargne et le pouvoir d’achat. Trop peu (la déflation) pousse à reporter ses achats, ce qui freine l’économie.'],
    calc:{title:'Ton panier de courses avec 2 % d’inflation par an', rows:[['Aujourd’hui','100,00 €'],['Dans 1 an','102,00 €'],['Dans 5 ans','110,41 €'],['Dans 10 ans','121,90 €']]},
    you:'Si ton salaire augmente moins vite que les prix, ton pouvoir d’achat baisse même si ta fiche de paie grimpe. Pareil pour un livret d’épargne qui rapporte moins que l’inflation.',
    quiz:{q:'Ton livret rapporte 1,5 % et l’inflation est de 3 %. Que se passe-t-il ?', opts:['Tu t’enrichis de 1,5 %','Ton épargne perd du pouvoir d’achat','Rien ne change'], a:1, why:'Ton argent grossit de 1,5 % mais les prix de 3 %. Au final, tu peux acheter environ 1,5 % de choses en moins.'},
    related:['taux','pib']},
  taux:{icon:'taux', title:'Les taux directeurs', short:'Le thermostat des banques centrales', minutes:5,
    one:'Le taux directeur est le prix auquel la banque centrale (la BCE pour la zone euro) prête de l’argent aux banques. Il sert à accélérer ou freiner l’économie.',
    analogy:'C’est le thermostat de l’économie. Quand ça « chauffe » trop (inflation forte), la banque centrale monte le taux pour refroidir. Quand l’économie est trop froide, elle le baisse pour relancer.',
    chain:[['La BCE monte son taux','Emprunter coûte plus cher aux banques.'],['Les banques suivent','Elles relèvent les taux des crédits immobiliers, auto, conso.'],['On emprunte moins','Ménages et entreprises reportent achats et investissements.'],['La demande ralentit','Les entreprises ont plus de mal à augmenter leurs prix.'],['L’inflation baisse','C’est l’objectif, avec un risque de freiner la croissance.']],
    how:['La BCE vise une inflation de 2 % à moyen terme dans la zone euro.','Aux États-Unis, c’est la Réserve fédérale (la « Fed ») qui joue ce rôle.','L’effet n’est pas immédiat : il faut souvent plus d’un an pour qu’une hausse de taux se voie sur les prix.'],
    you:'Les taux directeurs pèsent sur le coût de ton crédit immobilier et sur ce que rapporte ton épargne. Quand ils montent, emprunter coûte plus cher mais l’épargne rapporte davantage.',
    quiz:{q:'L’inflation est très forte. Que fait en général la banque centrale ?', opts:['Elle baisse ses taux','Elle monte ses taux','Elle imprime des billets'], a:1, why:'Monter les taux rend le crédit plus cher, ce qui calme la demande et donc la hausse des prix.'},
    related:['inflation','pib']},
  commerce:{icon:'commerce', title:'Le commerce international', short:'Pourquoi les pays échangent', minutes:4,
    one:'Le commerce international, ce sont les biens et services qu’un pays vend (exportations) et achète (importations) à d’autres pays.',
    analogy:'Toi, tu cuisines bien ; ton voisin répare bien les vélos. Plutôt que chacun fasse tout moyennement, vous vous spécialisez et échangez. Les pays font pareil, à grande échelle.',
    how:['Chaque pays se spécialise dans ce qu’il fait relativement le mieux : c’est l’« avantage comparatif ».','La balance commerciale compare exportations et importations. Un déficit veut dire qu’on achète plus qu’on ne vend.','Les droits de douane sont des taxes sur les importations. Ils protègent certains producteurs locaux mais renchérissent les produits pour les consommateurs.','Les chaînes de production sont mondiales : un téléphone peut contenir des pièces de plus de dix pays.'],
    you:'Les prix de ton téléphone, de tes vêtements ou de ton café dépendent des échanges mondiaux, des taux de change et des droits de douane.',
    quiz:{q:'Qui paie d’abord un droit de douane sur un produit importé ?', opts:['Le pays exportateur','L’entreprise qui importe le produit','Personne'], a:1, why:'C’est l’importateur qui le règle à la douane. Il le répercute souvent ensuite, en partie, sur le prix payé par le client.'},
    related:['omc','pib']},
  fmi:{icon:'fmi', title:'Le FMI', short:'Le pompier financier des pays', minutes:3,
    one:'Le Fonds monétaire international est une institution qui réunit 191 pays. Il surveille l’économie mondiale et prête aux pays en crise.',
    analogy:'C’est une caisse commune entre voisins. Chacun cotise, et celui qui traverse un coup dur peut emprunter, à condition de remettre de l’ordre dans ses comptes.',
    how:['Créé en 1944 à Bretton Woods, à la fin de la Seconde Guerre mondiale, pour éviter le retour des crises des années 1930.','Il prête aux pays qui n’arrivent plus à payer leurs dettes ou à financer leurs importations.','En échange, il impose souvent des conditions : réduire les dépenses, réformer les impôts. C’est ce qui le rend controversé.','Il publie des prévisions de croissance suivies par les gouvernements et les médias.'],
    you:'Quand tu lis « le FMI prévoit 3 % de croissance mondiale », c’est l’un de ses rôles : prévoir et alerter.',
    quiz:{q:'Que demande souvent le FMI en échange d’un prêt ?', opts:['Rien du tout','Des réformes économiques','Que le pays quitte l’ONU'], a:1, why:'Les prêts sont « conditionnels » : le pays s’engage sur des réformes, ce qui fait souvent débat.'},
    related:['omc','commerce']},
  omc:{icon:'omc', title:'L’OMC', short:'L’arbitre du commerce mondial', minutes:3,
    one:'L’Organisation mondiale du commerce fixe les règles des échanges entre ses 166 membres et règle leurs disputes commerciales.',
    analogy:'C’est l’arbitre d’un match où chaque équipe est un pays. Il y a un règlement commun, et un arbitre pour trancher quand quelqu’un triche.',
    how:['Créée en 1995 à Genève, elle a pris la suite du GATT (1947).','Principe clé : un avantage accordé à un pays doit l’être à tous les membres (clause de la nation la plus favorisée).','Son « tribunal » d’appel est bloqué depuis 2019, faute de juges nommés, ce qui affaiblit son rôle d’arbitre.'],
    you:'Les règles de l’OMC encadrent les droits de douane sur ce que tu achètes, des voitures aux produits agricoles.',
    quiz:{q:'Quel est le rôle principal de l’OMC ?', opts:['Imprimer la monnaie mondiale','Fixer les règles du commerce entre pays','Prêter aux pays en crise'], a:1, why:'Prêter aux pays en crise, c’est le FMI. L’OMC, elle, s’occupe des règles du commerce.'},
    related:['fmi','commerce']},
  pib:{icon:'pib', title:'Le PIB et la croissance', short:'Mesurer la richesse produite', minutes:3,
    one:'Le produit intérieur brut mesure la valeur de tout ce qui est produit dans un pays en un an. La croissance, c’est son évolution d’une année à l’autre.',
    analogy:'C’est le ticket de caisse géant d’un pays : on additionne la valeur de tout ce qui a été produit et vendu, du pain à l’assurance.',
    how:['Une récession, c’est généralement deux trimestres de suite de baisse du PIB.','Le PIB ne mesure ni le bien-être, ni les inégalités, ni les dégâts sur l’environnement.','On compare souvent le PIB par habitant pour mesurer le niveau de vie moyen.'],
    you:'Quand la croissance est forte, les entreprises embauchent plus. Quand elle ralentit, le chômage a tendance à monter.',
    quiz:{q:'Le PIB baisse deux trimestres d’affilée. On parle de…', opts:['Récession','Inflation','Déflation'], a:0, why:'C’est la définition la plus courante d’une récession.'},
    related:['inflation','taux']},
};

const NEWS = [
  {id:'bce', icon:'taux', cat:'Banques centrales', title:'La BCE laisse ses taux inchangés',
    lede:'La Banque centrale européenne a décidé de ne pas toucher à ses taux directeurs ce mois-ci.',
    tldr:'La BCE juge que l’inflation est revenue près de son objectif de 2 %. Elle préfère attendre avant de bouger, dans un sens ou dans l’autre.',
    what:'Le conseil des gouverneurs de la BCE se réunit environ toutes les six semaines. Cette fois, il a laissé le taux inchangé, après une série de baisses.',
    why:'Ne rien faire est aussi un message. La BCE estime que l’économie de la zone euro n’a besoin ni d’être relancée, ni d’être freinée pour l’instant.',
    you:['Les taux des crédits immobiliers devraient rester stables à court terme.','Le Livret A et les comptes d’épargne ne devraient pas bouger brutalement.'],
    topics:['taux','inflation']},
  {id:'douanes', icon:'commerce', cat:'Commerce', title:'Washington relève ses droits de douane sur l’acier européen',
    lede:'Les États-Unis annoncent une nouvelle taxe sur certaines importations venues d’Europe.',
    tldr:'Un droit de douane plus élevé rend l’acier européen plus cher aux États-Unis. L’Europe peut répliquer, et c’est le début possible d’une « guerre commerciale ».',
    what:'Le gouvernement américain augmente la taxe payée à la frontière sur l’acier importé d’Europe, pour protéger ses propres usines.',
    why:'Les entreprises européennes risquent de vendre moins aux États-Unis. Si l’Europe répond par ses propres taxes, les deux côtés paient plus cher. L’OMC peut être saisie pour trancher.',
    you:['Des produits qui contiennent de l’acier (voitures, électroménager) peuvent coûter plus cher.','Certains emplois industriels en Europe peuvent être fragilisés.'],
    topics:['commerce','omc']},
  {id:'petrole', icon:'oil', cat:'Énergie', title:'Le prix du pétrole grimpe après une décision de l’OPEP+',
    lede:'Les grands pays producteurs de pétrole ont décidé de réduire leur production.',
    tldr:'Moins de pétrole sur le marché pour la même demande, donc un prix plus élevé. Ça se retrouve vite à la pompe, puis dans d’autres prix.',
    what:'L’OPEP+ regroupe l’Arabie saoudite, la Russie et une vingtaine d’autres producteurs. Ils se mettent d’accord pour produire moins de barils chaque jour.',
    why:'Le pétrole sert à transporter presque tout ce qu’on achète. Quand il augmente, les coûts de transport et de production montent aussi, ce qui peut relancer l’inflation.',
    you:['Le plein d’essence coûte plus cher dans les semaines qui suivent.','Si la hausse dure, d’autres prix peuvent suivre, et la BCE peut hésiter à baisser ses taux.'],
    topics:['inflation','taux']},
];
